;;#========================================================
;;# ini for saving 3x2pt DV for a chain that originally ran 2x2pt posterior
;;#========================================================
; NOTE: %include the ini for the pipeline running the DV elements you want to save
;  *not* the same that produced the original chain. But make sure them model matches
; i.e. even though posterior is for 2x2pt, we want to save all 3x2pt DV elements

%include  params_for_3x2pt_chain_matching_model_usedfor_2x2pt_chain.ini

[pipeline]
; AS BEFORE: need to make sure # for extra_output is right
extra_output = data_vector/2pt_theory#1000
fast_slow=F
[runtime]
sampler = importance

[importance]
; This is where you put the chain with the posterior you want to sample
input = ${ORIG_CHAIN_DIR}/22pt_lcdm_fidsimy6.txt

[output]
filename = ${OUTPUT_DIR}/ppd.22pt_lcdm_fidsimy6-IS.txt


[2pt_like]
; let's save all the DV predictions, without the scale cuts
; (this can make the DV element counting simpler for extra_output)
angle_range_xip_1_1 = 0.0000 999.0000
angle_range_xip_1_2 = 0.0000 999.0000
angle_range_xip_1_3 = 0.0000 999.0000
angle_range_xip_1_4 = 0.0000 999.0000
angle_range_xip_2_2 = 0.0000 999.0000
angle_range_xip_2_3 = 0.0000 999.0000
angle_range_xip_2_4 = 0.0000 999.0000
angle_range_xip_3_3 = 0.0000 999.0000
angle_range_xip_3_4 = 0.0000 999.0000
angle_range_xip_4_4 = 0.0000 999.0000
angle_range_xim_1_1 = 0.0000 999.0000
angle_range_xim_1_2 = 0.0000 999.0000
angle_range_xim_1_3 = 0.0000 999.0000
angle_range_xim_1_4 = 0.0000 999.0000
angle_range_xim_2_2 = 0.0000 999.0000
angle_range_xim_2_3 = 0.0000 999.0000
angle_range_xim_2_4 = 0.0000 999.0000
angle_range_xim_3_3 = 0.0000 999.0000
angle_range_xim_3_4 = 0.0000 999.0000
angle_range_xim_4_4 = 0.0000 999.0000
angle_range_gammat_1_1 = 0.0000 999.0000
angle_range_gammat_1_2 = 0.0000 999.0000
angle_range_gammat_1_3 = 0.0000 999.0000
angle_range_gammat_1_4 = 0.0000 999.0000
angle_range_gammat_2_1 = 0.0000 999.0000
angle_range_gammat_2_2 = 0.0000 999.0000
angle_range_gammat_2_3 = 0.0000 999.0000
angle_range_gammat_2_4 = 0.0000 999.0000
angle_range_gammat_3_1 = 0.0000 999.0000
angle_range_gammat_3_2 = 0.0000 999.0000
angle_range_gammat_3_3 = 0.0000 999.0000
angle_range_gammat_3_4 = 0.0000 999.0000
angle_range_gammat_4_1 = 0.0000 999.0000
angle_range_gammat_4_2 = 0.0000 999.0000
angle_range_gammat_4_3 = 0.0000 999.0000
angle_range_gammat_4_4 = 0.0000 999.0000
angle_range_gammat_5_1 = 0.0000 999.0000
angle_range_gammat_5_2 = 0.0000 999.0000
angle_range_gammat_5_3 = 0.0000 999.0000
angle_range_gammat_5_4 = 0.0000 999.0000
angle_range_wtheta_1_1 = 0.0000 999.0000
angle_range_wtheta_2_2 = 0.0000 999.0000
angle_range_wtheta_3_3 = 0.0000 999.0000
angle_range_wtheta_4_4 = 0.0000 999.0000
angle_range_wtheta_5_5 = 0.0000 999.0000
