;;#========================================================
;;# ini for saving 3x2pt DV for a chain that originally ran 3x2pt posterior
;;#========================================================

; Will use samples from the chain output in
;    ${ORIG_CHAIN_DIR}/32pt_lcdm_fidsimy6.txt
; Saving DV for pipeline matching that in 
;    params file: run_ini/params_for_original_chain_3x2pt.ini
;; BUT USING NO SCALE CUTS


%include  params_for_original_chain_3x2pt.ini
[pipeline]
;the trickiest piece here is making sure we count the number of DV elements
; correctly for this extra_output. In earlier tests I was doing 1000 was the right number
; for max angle of 250”, but we need a higher number for the DV with more elements

extra_output = data_vector/2pt_theory#1000
fast_slow=F

[runtime]
sampler = importance

[importance]
input = ${ORIG_CHAIN_DIR}/32pt_lcdm_fidsimy6.txt

[output]
filename = ${OUTPUT_DIR}/ppd.32pt_lcdm_fidsimy6-IS.txt


[2pt_like]
; let's save all the DV predictions, without the scale cuts
; (this can make the DV element counting simpler for extra_output)
angle_range_xip_1_1 = 0.0000 999.0000
angle_range_xip_1_2 = 0.0000 999.0000
angle_range_xip_1_3 = 0.0000 999.0000
angle_range_xip_1_4 = 0.0000 999.0000
angle_range_xip_2_2 = 0.0000 999.0000
angle_range_xip_2_3 = 0.0000 999.0000
angle_range_xip_2_4 = 0.0000 999.0000
angle_range_xip_3_3 = 0.0000 999.0000
angle_range_xip_3_4 = 0.0000 999.0000
angle_range_xip_4_4 = 0.0000 999.0000
angle_range_xim_1_1 = 0.0000 999.0000
angle_range_xim_1_2 = 0.0000 999.0000
angle_range_xim_1_3 = 0.0000 999.0000
angle_range_xim_1_4 = 0.0000 999.0000
angle_range_xim_2_2 = 0.0000 999.0000
angle_range_xim_2_3 = 0.0000 999.0000
angle_range_xim_2_4 = 0.0000 999.0000
angle_range_xim_3_3 = 0.0000 999.0000
angle_range_xim_3_4 = 0.0000 999.0000
angle_range_xim_4_4 = 0.0000 999.0000
angle_range_gammat_1_1 = 0.0000 999.0000
angle_range_gammat_1_2 = 0.0000 999.0000
angle_range_gammat_1_3 = 0.0000 999.0000
angle_range_gammat_1_4 = 0.0000 999.0000
angle_range_gammat_2_1 = 0.0000 999.0000
angle_range_gammat_2_2 = 0.0000 999.0000
angle_range_gammat_2_3 = 0.0000 999.0000
angle_range_gammat_2_4 = 0.0000 999.0000
angle_range_gammat_3_1 = 0.0000 999.0000
angle_range_gammat_3_2 = 0.0000 999.0000
angle_range_gammat_3_3 = 0.0000 999.0000
angle_range_gammat_3_4 = 0.0000 999.0000
angle_range_gammat_4_1 = 0.0000 999.0000
angle_range_gammat_4_2 = 0.0000 999.0000
angle_range_gammat_4_3 = 0.0000 999.0000
angle_range_gammat_4_4 = 0.0000 999.0000
angle_range_gammat_5_1 = 0.0000 999.0000
angle_range_gammat_5_2 = 0.0000 999.0000
angle_range_gammat_5_3 = 0.0000 999.0000
angle_range_gammat_5_4 = 0.0000 999.0000
angle_range_wtheta_1_1 = 0.0000 999.0000
angle_range_wtheta_2_2 = 0.0000 999.0000
angle_range_wtheta_3_3 = 0.0000 999.0000
angle_range_wtheta_4_4 = 0.0000 999.0000
angle_range_wtheta_5_5 = 0.0000 999.0000