#!/bin/bash
#SBATCH -J ppd_y6_rehv2
#SBATCH -A mynerscallocation
#SBATCH -q shared
#SBATCH -t 10:00:00
#SBATCH -C gpu
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 32
#SBATCH --gpus-per-node=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=myemail@place.edu
#SBATCH --output=JOB_OUT_%x_%j.txt
#SBATCH --error=JOB_ERR_%x_%j.txt

export SLURM_CPU_BIND="cores"
export Y6WORKSPACE="/global/homes/j/jmuir/y6-3x2pt/inference"

cd ${Y6WORKSPACE}/ppd
source setup_ppd_env_nersc.sh

srun python run_ppd_calcs_example.py

